name: UI Lint & Build

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './ui'

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "22.x"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Download OpenAPI Schema Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: schema.json
          path: ui

      - name: Build types
        run: yarn run openapi

      - name: Build Typescript
        run: yarn tsc

      - name: Lint TypeScript Code
        run: yarn lint

      - name: Build Dist
        run: yarn build

      - name: Upload Schema Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ui/build
          name: build
